name: Deploy Spring BE to EC2 with Jib and Docker

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "fe/**"
      - ".github/workflows/FE CD.yml"

env:
  DOCKER_IMAGE: seung093/playbaseball
  APP_DOMAIN: 3.38.149.152.nip.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images with Jib
        run: |
          ./gradlew jib -Pspring.profiles.active=prod
          ./gradlew jib -Pspring.profiles.active=debug

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Get EC2 private IP
          EC2_PRIVATE_IP=$(ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'curl -s http://169.254.169.254/latest/meta-data/local-ipv4')
          
          # Create .env file on EC2  
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            cat << EOT > .env
            RDS_HOST=${{ secrets.RDS_HOST }}
            RDS_PORT=${{ secrets.RDS_PORT }}
            RDS_NAME=${{ secrets.RDS_NAME }}
            RDS_USER=${{ secrets.RDS_USER }}
            RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
            JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }}
            JWT_EMAIL_VERIFICATION_EXPIRATION=${{ secrets.JWT_EMAIL_VERIFICATION_EXPIRATION }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            MAIL_PORT=${{ secrets.MAIL_PORT }}
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}  
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            S3_NAME=${{ secrets.S3_NAME }}
            S3_KEY=${{ secrets.S3_KEY }}
            S3_SECRET=${{ secrets.S3_SECRET }}
            ALAN_KEY=${{ secrets.ALAN_KEY }}
            ALAN_HOST=${{ secrets.ALAN_HOST }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            EC2_PRIVATE_IP=$EC2_PRIVATE_IP        
            APP_DOMAIN=${{ env.APP_DOMAIN }}
          EOT
          chmod 600 .env
          EOF

          # Remove old images and pull new ones
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            echo "Removing dangling images..."
            docker images --filter "dangling=true" -q | xargs -r docker rmi
            echo "Removing old versions of ${{ env.DOCKER_IMAGE }}..."  
            docker images | grep "${{ env.DOCKER_IMAGE }}" | grep -v "v2prod" | grep -v "v2debug" | awk '{print $3}' | xargs -r docker rmi
            echo "Pulling new images..."
            docker pull ${{ env.DOCKER_IMAGE }}:v2prod
            docker pull ${{ env.DOCKER_IMAGE }}:v2debug
            echo "Remaining images:"
            docker images  
          EOF

          # Deploy prod image
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            docker stop play-baseball-server || true
            docker rm play-baseball-server || true
            docker run -d --name play-baseball-server \
              --env-file .env \
              -p 8080:8080 \
              ${{ env.DOCKER_IMAGE }}:v2prod
          EOF

          rm -f private_key.pem

      - name: Check container logs
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem  
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            timeout 30s docker logs -f play-baseball-server || true
          EOF
          rm -f private_key.pem